stages:
  data_ingestion:
    cmd: python src/components/01_data_ingestion.py --config=params.yaml
    deps:
    - src/components/read_params.py
    - notebook/data/student.csv
    outs:
    - artifacts/raw/raw.csv
    - artifacts/processed/train.csv
    - artifacts/processed/test.csv

  data_transformation:
    cmd: python src/components/02_data_transformation.py --config=params.yaml
    deps:
    - src/components/read_params.py
    - artifacts/processed/test.csv
    - artifacts/processed/train.csv
    params:
    - estimators.RandomForest_regressor.params.n_estimators
    - estimators.RandomForest_regressor.params.criterion
    - estimators.RandomForest_regressor.params.max_depth
    outs:
    - artifacts/pre_processed/train.csv
    - artifacts/pre_processed/test.csv

  model_training:
    cmd: python src/components/03_model_trainer.py --config=params.yaml
    deps:
    - src/components/read_params.py
    - src/utils.py
    - artifacts/pre_processed/train.csv
    - artifacts/pre_processed/test.csv
    params:
    - estimators.RandomForest_regressor.params.n_estimators
    - estimators.RandomForest_regressor.params.criterion
    - estimators.RandomForest_regressor.params.max_depth
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - model/model.pkl