base:
  project: ML_Regression
  random_state: 42
  target_col: average_score
  numerical_columns: ["writing_score", "reading_score"]
  categorical_columns: ["gender","race_ethnicity","parental_level_of_education","lunch","test_preparation_course"]

data_source:
  DB_source: notebook/data/student.csv

load_data:
  raw_dataset_csv: artifacts/raw/raw.csv

split_data:
  train_path: artifacts/processed/train.csv
  test_path: artifacts/processed/test.csv
  test_size: 0.2

preprocessed_split_data:
  train_path: artifacts/pre_processed/train.csv
  test_path: artifacts/pre_processed/test.csv

preprocessor_obj_path: artifacts/pre_processed_obj/pre_processed_obj.pkl

estimators:
  RandomForest_regressor:
    params:
      n_estimators: 10
      criterion: "squared_error"
      max_depth: 5

model_dir: model/model.pkl

reports:
  params: report/params.json
  scores: report/scores.json
